// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Core = require("@material-ui/core");

function Header(Props) {
  Props.siteTitle;
  return React.createElement("header", undefined, React.createElement(Core.AppBar, {
                  position: "static"
                }));
}

var make = Header;

var $$default = Header;

exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* react Not a pure module */
