// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Css = require("bs-css/src/Css.js");
var React = require("react");
var Gatsby = require("gatsby");

var header = Css.style({
      hd: Css.backgroundColor(Css.hex("db4d3f")),
      tl: {
        hd: Css.marginBottom(Css.px(16)),
        tl: /* [] */0
      }
    });

var content = Css.style({
      hd: Css.display("flex"),
      tl: {
        hd: Css.alignItems("center"),
        tl: {
          hd: Css.justifyContent("spaceBetween"),
          tl: {
            hd: Css.margin2(Css.px(0), "auto"),
            tl: {
              hd: Css.maxWidth(Css.px(1000)),
              tl: {
                hd: Css.padding2(Css.px(16), Css.px(24)),
                tl: /* [] */0
              }
            }
          }
        }
      }
    });

var h1 = Css.style({
      hd: Css.margin(Css.px(0)),
      tl: /* [] */0
    });

var link = Css.style({
      hd: Css.color(Css.white),
      tl: {
        hd: Css.textDecoration(Css.none),
        tl: /* [] */0
      }
    });

var nav = Css.style(/* [] */0);

var Styles = {
  header: header,
  content: content,
  h1: h1,
  link: link,
  nav: nav
};

function Header(Props) {
  var siteTitle = Props.siteTitle;
  return React.createElement("header", {
              className: header
            }, React.createElement("div", {
                  className: content
                }, React.createElement("h1", {
                      className: h1
                    }, React.createElement(Gatsby.Link, {
                          to: "/",
                          className: link,
                          children: siteTitle
                        })), React.createElement("nav", {
                      className: nav
                    }, React.createElement(Gatsby.Link, {
                          to: "/blog",
                          className: link,
                          children: "Blog"
                        }))));
}

var make = Header;

var $$default = Header;

exports.Styles = Styles;
exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* header Not a pure module */
